config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#search'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :posts  

  root 'categories#index'
  resources :categories, only: [:show]

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  category_id   :integer
#  title         :string
#  description   :text
#  contact_name  :string
#  contact_no    :string
#  contact_email :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

require 'elasticsearch/model'

class Post < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  belongs_to :user
  belongs_to :category
end

Post.import force: true

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string           default(""), not null
#  phone                  :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index, :show]
  def index
    @categories = Category.all
  end

  def show
    category = Category.find(params[:id])
    @posts = Post.where(category_id:  category.id).order(id: :desc)
    # @post = Post.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index, :show]
  before_action :fetch_categories, only: [:new, :create, :edit, :update]
  
  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save!
      redirect_to posts_path
    else
      render :new
    end 
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = current_user.posts.order(id: :desc)
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :category_id, :description, 
                                   :contact_name, :contact_no, :contact_email)
    end

    def fetch_categories
      @categories = Category.all
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:search]
  def search
    if params[:q].nil?
      @posts = []
    else
      @posts = Post.search(params[:q])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |category| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://www.megaicons.net/static/img/icons_sizes/53/135/256/default-icon-icon.png" alt="default image">
      <div class="caption text-center">
        <h3><%= link_to category.name, category_path(category) %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<% @posts.each do |post| %>
  <h1><%= link_to post.title, post_path(post) %></h1> 
  <h3><%= post.description %></h3>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">De-classify</a> -->
      <%= link_to "De-Classify", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%= link_to "Post Ad", new_post_path, class: "btn btn-primary navbar-btn sweet" %>
        <%= link_to "Search", search_path,  class: "btn btn-primary navbar-btn" %>
        <% if user_signed_in? %>
          <%= link_to "My Ads", posts_path, class: "btn btn-primary navbar-btn" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-primary navbar-btn" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary navbar-btn" %>
        <% end %>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classifieds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/posts/edit.html.erb
<%= simple_form_for  @post  do |f| %>
  <%= f.input :title %>
  <%= f.input :category_id, collection: @categories %>
  <%= f.input :description, as: :text %>
  <%= f.input :contact_name %>
  <%= f.input :contact_no %>
  <%= f.input :contact_email %>
  <%= f.button :submit %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h1><%= post.title %></h1> 
  <h3><%= post.description %></h3>
  <%= link_to "Edit", edit_post_path(post), class: "btn btn-primary" %>
<% end %>

app/views/posts/new.html.erb
<%= simple_form_for  [@user, @post]  do |f| %>
  <%= f.input :title %>
  <%= f.input :category_id %>
  <%= f.input :description, as: :text %>
  <%= f.input :contact_name %>
  <%= f.input :contact_no %>
  <%= f.input :contact_email %>
  <%= f.button :submit %>
<% end %>

app/views/posts/show.html.erb
<h1><strong>Title :</strong><%= @post.title %></h1>
<h3><strong>Post Description :</strong><%= @post.description %></h3>
<h4><strong>Contact Name :</strong> <%= @post.contact_name %></h4>
<h4><strong>Contact Email :</strong> <%= @post.contact_email %></h4>
<h4><strong>Contact Number :</strong> <%= @post.contact_no %></h4>

app/views/search/search.html.erb
<h1>Post Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <h3>
        <%= link_to post.title, controller: "posts", action: "show", id: post._id%>
      </h3>
    </li>
  <% end %>
</ul>